apiVersion: v1
kind: Service
metadata:
  name: guestbook-stable
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-canary
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
