apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook-ui
spec:
  replicas: 5
  selector:
    matchLabels:
      app: guestbook-ui
  strategy:
    canary:
      canaryService: guestbook-canary
      stableService: guestbook-stable
      steps:
      - setWeight: 20       
      - pause: {100}
      - setWeight: 40       
      - pause: {duration: 10}
      - setWeight: 100      
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - name: guestbook-ui
        image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/hashicorp/http-echo:1.0
        # image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/argoproj/rollouts-demo:green
        args:
          - "-text=$(POD_TEXT)"  
        env:
        - name: POD_TEXT         
          value: "hello-world-green"
        ports:
        - containerPort: 5678
