apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf  # 覆盖容器内默认的 nginx.conf
          subPath: nginx.conf               # 指定挂载 ConfigMap 中的具体键名
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config                # 对应上面创建的 ConfigMap 名称
