apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort  # 指定服务类型为 NodePort
  selector:
    app: nginx  # 关联带有 app: nginx 标签的 Pod
  ports:
    - protocol: TCP
      port: 80        # 集群内部 Service 访问的端口
      targetPort: 80  # 转发到后端 Pod 的端口（对应 Deployment 中的 containerPort）
      nodePort: 30080 # 暴露给集群外部的节点端口（范围通常为 30000-32767）
