apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes auto;

    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        # 核心配置：使用 map 指令根据请求头 $http_x_env 的值映射到不同的后端服务名
        # Nginx 会自动将 Header 中的短横线(-)转换为下划线(_)，且变量名统一为小写
        map $http_x_env $backend_service {
            default   "guestbook-stable:5678";  # 默认转发到 gray 环境
            "prd"     "guestbook-stable:5678";   # 当 x_env=prd 时，转发到 prd 环境
            "gray"    "guestbook-canary:5678";  # 当 x_env=gray 时，转发到 gray 环境
        }

        server {
            listen 80;
            server_name localhost;

            resolver 10.96.0.10 valid=5s;
            resolver_timeout 5s;

            location / {

                # 动态代理：将请求转发给 map 映射出的后端 Service
                # 注意：在 K8s 中，Service 可以通过其名称（DNS）直接访问
                proxy_pass http://$backend_service;
                
                # 传递必要的请求头信息给后端
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
